programs:
  ping:
    cmd: 'ping 8.8.8.8'
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
      - 143
    startretries: 3
    starttime: 2
    stopsignal: SIGTERM
    stoptime: 2
    stdout: /tmp/ping.stdout
    stderr: /tmp/ping.stderr
    env:
      STARTED_BY: taskmaster
# 143 signal is for docker
