programs:
  nginx:
    cmd: '/usr/sbin/nginx -g "daemon off;" -c /etc/nginx/conf.d/mynginx.conf'
    numprocs: 2
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 2
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
