programs:
  nginx:
    cmd: '/usr/sbin/nginx -c /etc/nginx/conf.d/mynginx.conf'
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
  apache:
    cmd: '/usr/sbin/apache2'
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
